# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mongodb-primary:
    image: bitnami/mongodb:latest
    ports:
      - 0.0.0.0:27017:27017
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
volumes:
  mongodb_master_data:
    driver: local