package types

const (
	TransactionTypeTransfer = 1
	TransactionTypePayment  = 2
)

type TransactionValidateInfo struct {
	TransactionID       string
	Amount              int64
	SourceAccountNumber string
	TransactionType     int
	Destination         string
	BankCode            string
}

type TransactionValidateReplyInfo struct {
	ReplyID           string // generated by money service
	AvailableBalance  int64
	BalanceSufficient bool
	TransactionValidateInfo
}
